name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./gcp-terraformcode-module-gke/environment/prod
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7   # Use the desired Terraform version
     
      - name: Setup terraform variables
        id: vars
        run: |-
          cat > pipeline.auto.tfvars <<EOF
          password="${{ vars.PWD }}" 
          EOF
          
      - name: Terraform Init
        run: terraform init 
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}  
                
      - name: Plan
        run: terraform plan -lock=false -input=false
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} 
 
#      - name: Deploy
#        run: |
#          terraform destroy -lock=false --auto-approve -input=false
#        env:
#          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

  deploy-dr:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./gcp-terraformcode-module-gke/environment/dr
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7   # Use the desired Terraform version
 
      - name: Terraform Init
        run: terraform init 
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}  
                
      - name: Plan
        run: terraform plan -lock=false -input=false
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} 
 
      - name: Deploy
        run: |
          terraform apply -lock=false --auto-approve -input=false
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Cleanup
        run: rm -f tfplan
