name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./gcp-terraformcode-module-gke/environment/dr
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.7   # Use the desired Terraform version

    - name: Terraform Init
      run: terraform init 
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}  
                
    - name: Plan
      run: terraform plan -input=false
      
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} 
 
  
#    - name: Deploy
#      run: |
#       terraform apply --auto-approve


    - name: Cleanup
      run: rm -f tfplan
