name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.7   # Use the desired Terraform version

    - name: Terraform Init
      run: terraform init gcp-terraformcode-module-gke/environment/prod
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}  
                
    - name: Plan
      run: terraform plan gcp-terraformcode-module-gke/environment/prod 
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} 
 
  
#    - name: Deploy
#      run: |
#       terraform apply --auto-approve
#      env:
#        TF_VAR_variable_name: ${{ secrets.TF_VAR_variable_name }}
      # You can set additional environment variables here

    - name: Cleanup
      run: rm -f tfplan
