# This is a basic workflow to help you get started with Actions

name: GKE_Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "wordpress" ]
  #pull_request:
   # branches: [ "main" ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
      
      - name: google Auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Install kubectl
        run: |
         sudo apt-get install apt-transport-https ca-certificates gnupg
         echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
         echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
         curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
         curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
         curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /usr/share/keyrings/cloud.google.gpg
         sudo apt-get update && sudo apt-get install google-cloud-cli
         sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin
         gcloud init
         RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-cli -y
      #   RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | tee /usr/share/keyrings/cloud.google.gpg && apt-get update -y && apt-get install google-cloud-sdk -y
        
      - name: Set GCP Project ID
        run: gcloud config set project poc-ansible-tomcat
      
      - name: Set GKE Cluster
        run: gcloud container clusters get-credentials cluster-prod --zone europe-north1
     
      - name: Run build
        run: docker build -t  demo-wordpress .
        
      - name: image  tag
        run: |
          docker tag demo-wordpress sitharamaneesh/demo-wordpress
          #docker tag mariadb:10.5.8  sitharamaneesh/mariadb:10.5.8       
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: '${{ secrets.DOCKER_USER }}'
          password: '${{ secrets.DOCKER_PWD }}'
          
      - name: Docker push
        run: |
          docker push sitharamaneesh/demo-wordpress:latest
          #docker push sitharamaneesh/mariadb:10.5.8
          
      - name: deploy
        run: kubectl apply -f deployment.yaml

      - name: Set GKE Cluster
        run: gcloud container clusters get-credentials cluster-dr --zone us-central1
      - name: deploy
        run: kubectl apply -f deployment-dr.yaml
